"""Dropping server default

Revision ID: ac365a3e271c
Revises: 657f28935868
Create Date: 2021-11-22 14:48:02.709357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ac365a3e271c"
down_revision = "657f28935868"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "syft_user",
        "id",
        server_default = None,
        existing_nullable=False,
        existing_server_default=False,
    )

    op.execute("UPDATE syft_user SET id = LPAD(id, 32, '0')")
    op.execute("UPDATE request SET user_id = LPAD(user_id, 32, '0')")
    op.execute("UPDATE userenvironment SET user_id = LPAD(user_id, 32, '0')")
    op.execute("UPDATE usergroup SET user_id = LPAD(user_id, 32, '0')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
