"""id->UUID

Revision ID: 3a881d611983
Revises: ac365a3e271c
Create Date: 2021-11-22 14:53:18.443932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3a881d611983"
down_revision = "ac365a3e271c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request",
        "user_id",
        existing_type=sa.VARCHAR(length=36),
        type_=postgresql.UUID(as_uuid=True),
        existing_nullable=True,
        postgresql_using='user_id::UUID'
    )
    op.alter_column(
        "syft_user",
        "id",
        existing_type=sa.VARCHAR(length=36),
        type_=postgresql.UUID(as_uuid=True),
        existing_nullable=False,
        postgresql_using='id::UUID'
    )
    op.alter_column(
        "userenvironment",
        "user",
        existing_type=sa.VARCHAR(length=36),
        type_=postgresql.UUID(as_uuid=True),
        existing_nullable=True,
        postgresql_using='user::UUID'
    )
    op.alter_column(
        "usergroup",
        "user",
        existing_type=sa.VARCHAR(length=36),
        type_=postgresql.UUID(as_uuid=True),
        existing_nullable=True,
        postgresql_using='user::UUID'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
