"""Dropping constraints

Revision ID: f72585fbedda
Revises: 07fb4c284883
Create Date: 2021-11-22 13:20:33.711417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f72585fbedda"
down_revision = "07fb4c284883"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("request_user_id_fkey", "request", type_="foreignkey")
    op.drop_constraint(
        "userenvironment_user_fkey", "userenvironment", type_="foreignkey"
    )
    op.drop_constraint("usergroup_user_fkey", "usergroup", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "usergroup_user_fkey", "usergroup", "syft_user", ["user"], ["id"]
    )
    op.create_foreign_key(
        "userenvironment_user_fkey",
        "userenvironment",
        "syft_user",
        ["user"],
        ["id"],
    )
    op.create_foreign_key(
        "request_user_id_fkey", "request", "syft_user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
