"""Recreating constraints

Revision ID: a6c219dc7535
Revises: 3a881d611983
Create Date: 2021-11-22 18:02:00.446763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a6c219dc7535"
down_revision = "3a881d611983"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "request", "syft_user", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "userenvironment", "syft_user", ["user_id"], ["id"]
    )
    op.create_foreign_key(None, "usergroup", "syft_user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usergroup", type_="foreignkey")
    op.drop_constraint(None, "userenvironment", type_="foreignkey")
    op.drop_constraint(None, "syft_user", type_="foreignkey")
    op.drop_constraint(None, "request", type_="foreignkey")
    # ### end Alembic commands ###
